name: Test Runner

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [self-hosted, k8s, linux]
    steps:
      - name: Print message
        run: echo "🎉 Self-hosted runner is working!"
